package io.projectZ;

import io.projectZ.provider.JwtAuthProvider;
import org.jivesoftware.openfire.auth.ConnectionException;
import org.jivesoftware.openfire.auth.InternalUnauthenticatedException;
import org.jivesoftware.openfire.auth.UnauthorizedException;

public class Main {
    public static void main(String[] args) throws UnauthorizedException, InternalUnauthenticatedException, ConnectionException {
        JwtAuthProvider provider = new JwtAuthProvider();
        provider.authenticate("nafiseh" , "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJPSlh4RUk0YTY0c2V1eHU2Rmk3WjZUdUhIQjdBc2luZ0JPS2ljZUJTU1EwIn0.eyJleHAiOjE3ODMwNzIzOTYsImlhdCI6MTc4MzA3MjA5NiwianRpIjoib25ydHJvOjQ4MDY2ZDNkLTY0MmUtNmFlMi1mYjBlLWIzZjlmM2IwNDllZCIsImlzcyI6Imh0dHA6Ly8xMzAuMTg1LjEyMS4xNzM6ODA4MS9yZWFsbXMvcHJvamVjdC16IiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjYyZGJiM2Y3LTk0NzgtNGQyZi1hNmNlLTU1MzliZjJmMGQ2ZCIsInR5cCI6IkJlYXJlciIsImF6cCI6InotY2hhdCIsInNpZCI6IkRqQ1VKZlFCQWs5MkNCY3BEZnhadjhTYiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXByb2plY3QteiIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJuYWZpc2VoIGhhZGRhZGkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJuYWZpc2VoIiwiZ2l2ZW5fbmFtZSI6Im5hZmlzZWgiLCJmYW1pbHlfbmFtZSI6ImhhZGRhZGkiLCJlbWFpbCI6ImVmdGVraGFyZWFmYWdoLjE5MDNAZ21haWwuY29tIn0.ohFpBbFST3s-GKo2G3TRvBmt3a9WKsJTmyJuYTt_STGxdgCBqAmB9C1jpbSB0e_chxWjDi1HPsBqqRWU0GrbMutSFBf-L1PvL9CMQfN2_-6_kDfZmtcWoSFmziZt3S8pY2egAkdOztmKxZIws0dy8qj7ZaRXRQ2b1AmT4CgP_gVWPi9gw0Q6SSJgv5nbAOTzGXPhiOTO611ec03Hd5TduEcoHqwlVWZR27r5YpBmpNK_69PIcFpLCTSiH7dG2dc8IeUWvlFMOfaPL93-3E9jVVDRdYc83ChN6ez4fOKkVAqMjphsPoCaOxwDP7QIDzfzsu253WLJP3nYcDLkn4yn-w");
        System.out.println("everything is ok");
    }
}